version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.12  # Adjust based on your component's runtime needs
  build:
    commands:
      - echo "Building Greengrass component"
      - zip -r component.zip src/component_code/requirements.txt src/component_code/test.py  # Example: packaging source files
  post_build:
    commands: 
      - echo "Saving artifact to S3"
      - aws s3 cp component.zip s3://gg-component-test-bucket-2/component.zip
artifacts:
  files:
    - component.zip 